// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmkcxsyudgtimpbjwcjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZta2N4c3l1ZGd0aW1wYmp3Y2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDcyNTcsImV4cCI6MjA5MDEyMzI1N30.P5QCe2ZlRQBE8ZkCFTMRI26Zm7yTqk9bzPx39Rs83yE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});